export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const LOAD_SYMBOLS = "LOAD_SYMBOLS";
export const BASE_CURRENCY = "BASE_CURRENCY";
export const GET_CMP = "GET_CMP";
export const CONVERT_CURRENCIES = "CONVERT_CURRENCIES";
export const COMPARE_CURRENCIES = "COMPARE_CURRENCIES";
export const CURRENCY_PERFORMANCE = "CURRENCY_PERFORMANCE";
